# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Geovation Tech
tagline:          'Exploring the frontiers of innovation'
description:      'Searching for technical insight in the uncharted wilderness.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Geovation stuff
gems: [jekyll-paginate, jekyll-gist]
