# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Geovation Tech
tagline:          'Engineering Blog'
description:      'Searching for technical insight in the uncharted wilderness.'
url:              http://tech.geovation.uk
baseurl:          /

author:
  name:           'Geovation'
  url:            https://geovation.uk/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Geovation/geovation.github.io

# Geovation stuff
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]
