# docker-compose up

version: "3"

services:
  jekill:
    container_name: jekyll
    image: jekyll/jekyll
    volumes:
      - .:/srv/jekyll
    command: jekyll build --watch
    # command: bundle update
