# docker-compose up

version: "3"

services:
  jekyll:
    container_name: jekyll
    image: jekyll/jekyll:3
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    # command: jekyll build --watch
    # command: bundle update
    command: jekyll serve
